- name: Create project folder structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0755'
  with_items:
    - "{{ project_dir | expanduser }}"
    
- name: Create docker volumes
  community.docker.docker_volume:
    name: "{{ item }}"
  with_items:
    - "{{ acme_volume }}"
    - "{{ plex_volume }}"
    - "{{ plex_transcode_volume }}"
    - "{{ tautulli_volume }}"

- name: Create NFS Data share volume
  community.docker.docker_volume:
    name: "{{ nfs_data_volume }}"
    driver: local
    driver_options:
      type: nfs
      o: "addr={{ nfs_data_server }},nolock,noatime,soft,rw"
      device: ":{{ nfs_data_device }}"

- name: Create docker network {{ common.network.name }}
  community.docker.docker_network:
    name: "{{ network_name }}"

- name: Start docker images
  ansible.builtin.import_tasks: ../tasks/docker-compose-up.yml