- name: Create project folder structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: '0755'
  with_items:
    - "{{ project_dir | expanduser }}"
    
- name: Create docker volumes
  community.docker.docker_volume:
    name: "{{ item }}"
  with_items:
    - "{{ acme_volume }}"
    - "{{ plex_volume }}"
    - "{{ plex_transcode_volume }}"
    - "{{ tautulli_volume }}"
    - "{{ tdarr_server_volume }}"
    - "{{ tdarr_config_volume }}"
    - "{{ tdarr_logs_volume }}"
    - "{{ tdarr_cache_volume }}"

- name: Create NFS Data share volume
  community.docker.docker_volume:
    name: "{{ data_volume }}"
    driver: local
    driver_options:
      type: nfs4
      o: "addr={{ nfs_data_server }},,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":{{ nfs_data_device }}"
  when: data_volume_type == 'nfs'

- name: Create SMB Data share volume
  community.docker.docker_volume:
    name: "{{ data_volume }}"
    driver: local
    driver_options:
      type: cifs
      o: "username={{ cifs_data_username }},password={{ cifs_data_password }},file_mode=0777,dir_mode=0777"
      device: "//{{ cifs_data_server }}/{{ cifs_data_device }}"
  when: data_volume_type == 'cifs'

- name: Create docker network {{ common.network.name }}
  community.docker.docker_network:
    name: "{{ network_name }}"

- name: Start docker images
  ansible.builtin.import_tasks: ../tasks/docker-compose-up.yml